/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIIT.stud;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Dev
 */
public final class Submit extends javax.swing.JInternalFrame {
String numOfQuestions, RBans, ques, a, b, c, d, ans, sol, SQL, course;
Boolean[] attempted;
int totalAttempted=0, count=0, incorrect=0, correct=0, cat=0, counter = 0;
int categ[], categTrue[] , categTotal[];

showQues QuesFrame;
Connection con ;
Statement stmt1=null, stmt2=null;
ResultSet rs;

Main chkFrame;
Timer t;
result r;

    /**
     * Creates new form Submit
     * @param s
     * @param atempted
     * @param previous
     */
    public Submit(String s, Boolean[] atempted, Main chkFrame,String course, showQues previous) {
        initComponents();
        this.numOfQuestions = s;
        this.attempted = atempted;
        this.count = Integer.parseInt(numOfQuestions);
        this.chkFrame = chkFrame;
        this.course = course;
        totalAttempted = count;
        categ = new int[count];
        QuesFrame = previous;
        numQ.setText(numOfQuestions);
        get_total_category();
        getCategOfQues(categ);
        setAttempted(atempted);
        showattempted.setText(Integer.toString(totalAttempted));
        this.setLayer(1);
        
        wait.setVisible(false);
        t = new Timer(10, (ActionEvent e) -> {
            showResult();
            t.stop();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numOfQjLabel1 = new javax.swing.JLabel();
        attemptedjLabel2 = new javax.swing.JLabel();
        numQ = new javax.swing.JLabel();
        showattempted = new javax.swing.JLabel();
        submitjButton1 = new javax.swing.JButton();
        goBackjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        wait = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setTitle("Submit");
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(550, 315));
        setMinimumSize(new java.awt.Dimension(550, 315));
        setPreferredSize(new java.awt.Dimension(550, 315));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(476, 336));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        numOfQjLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        numOfQjLabel1.setText("Total number of questions");

        attemptedjLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        attemptedjLabel2.setText("Questions attempted");

        numQ.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        showattempted.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        submitjButton1.setText("Evaluate");
        submitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButton1ActionPerformed(evt);
            }
        });
        submitjButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitjButton1KeyPressed(evt);
            }
        });

        goBackjButton1.setText("Go Back");
        goBackjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackjButton1ActionPerformed(evt);
            }
        });
        goBackjButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                goBackjButton1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 23)); // NOI18N
        jLabel1.setText("     Confirm Test Submission   ");

        wait.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        wait.setText("Please wait, calculating Test Result.....");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(goBackjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(submitjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(attemptedjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numOfQjLabel1))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showattempted, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numQ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfQjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numQ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showattempted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptedjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(wait, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void get_total_category() {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root","");

        SQL = "SELECT * FROM `concepts " +course+ "`";

        Statement stmt = con.createStatement();
        rs = stmt.executeQuery(SQL);
        

        while(rs.next())
            counter++;
        categTrue = new int[counter];
        categTotal = new int[counter];
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Submit.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void goBackjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackjButton1ActionPerformed
        QuesFrame.setEnabled(true);
        QuesFrame.evalCancelled();
        this.setVisible(false);
    }//GEN-LAST:event_goBackjButton1ActionPerformed

    private void submitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButton1ActionPerformed
        wait.setVisible(true);
        t.start();
        QuesFrame.stopTimer();
    }//GEN-LAST:event_submitjButton1ActionPerformed

    private void goBackjButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_goBackjButton1KeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode()==KeyEvent.VK_ESCAPE)){
            goBackjButton1.doClick();
        }
    }//GEN-LAST:event_goBackjButton1KeyPressed

    private void submitjButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitjButton1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            submitjButton1.doClick();
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE)
            goBackjButton1.doClick();
    }//GEN-LAST:event_submitjButton1KeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE)
            goBackjButton1.doClick();
    }//GEN-LAST:event_jPanel1KeyPressed
    
    void setAttempted(Boolean[] check){
        for(int i = 0; i<count; i++){
            if(check[i] == null) {
               totalAttempted--;                 
            } 
            else if(check[i] == true){
                correct++;
                categTrue[categ[i]-1]++;
            }
            else
                incorrect++;
        }
     }

    void getCategOfQues(int array[]){
        try {
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root","");
            SQL = "SELECT * FROM "+course;

            stmt1 = con.createStatement();
            rs = stmt1.executeQuery(SQL);
            
            rs.first();
            for(int p=0; p<count; p++){
                cat = Integer.parseInt(rs.getString("category"));
                categ[p] = cat;
                categTotal[cat-1]++;
                if(!rs.next())
                    break;
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Submit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void forceSubmit(){
        goBackjButton1.setEnabled(false);
        submitjButton1.doClick();
    }
    
    private void showResult(){
        try { 
            r = new result(numOfQuestions, attempted, totalAttempted, correct, incorrect, QuesFrame, categTrue, categTotal, chkFrame, course, counter);
            this.getParent().add(r);
            
            setRootPaneCheckingEnabled(false);
            javax.swing.plaf.InternalFrameUI ifu= r.getUI();
            ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setSouthPane(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setEastPane(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setWestPane(null);
            
            r.setMaximum(true);
            r.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Submit.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateDataBase();
        QuesFrame.setVisible(false);
        this.dispose();
    }
    
     void updateDataBase(){
         int gotoStep = 0;
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root","");
            SQL = "SELECT * FROM "+course;

            stmt1 = con.createStatement();
            stmt2 = con.createStatement();
            
            rs = stmt1.executeQuery(SQL);

            int temp=0;
            while(temp!=count){
                rs.next();
                temp++;
            }
            //rs.next();
            
            while(true){
                ques = rs.getString("ques");
                a = rs.getString("a");
                b = rs.getString("b");
                c = rs.getString("c");
                d = rs.getString("d");
                ans = rs.getString("ans");
                cat = Integer.parseInt(rs.getString("category"));

                SQL = "INSERT INTO `tempques` (ques,a,b,c,d,ans,category, course) VALUES ('" +ques+ "','" +a+ "','" +b+ "','" +c+ "','" +d+ "','" +ans+ "','" +cat+ "','" +course+ "')";
                stmt2.executeUpdate(SQL);

                if(!rs.next()){
                    gotoStep = 1;
                    break;
                }
            }
            if(gotoStep == 1){
                rs.first();
                for(int j = 0 ; j<count; j++,rs.next())
                {
                    ques = rs.getString("ques");
                    a = rs.getString("a");
                    b = rs.getString("b");
                    c = rs.getString("c");
                    d = rs.getString("d");
                    ans = rs.getString("ans");
                    cat = Integer.parseInt(rs.getString("category"));
                    SQL = "INSERT INTO `tempques` (ques,a,b,c,d,ans,category,course) VALUES ('" +ques+ "','" +a+ "','" +b+ "','" +c+ "','" +d+ "','" +ans+ "','" +cat+ "','" +course+ "')";
                    stmt2.executeUpdate(SQL);
                }
                gotoStep = 2;
            }
            if(gotoStep == 2){
                SQL = "RENAME TABLE " +course+ " TO temp";
                stmt1.executeUpdate(SQL);
                SQL = "RENAME TABLE tempques TO "+course;
                stmt2.executeUpdate(SQL);
                SQL = "RENAME TABLE temp TO tempques";
                stmt1.executeUpdate(SQL);
                SQL = "DELETE FROM `tempques`";
                stmt1.executeUpdate(SQL);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showInternalMessageDialog(this,ex.getMessage());
        }
    }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attemptedjLabel2;
    private javax.swing.JButton goBackjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numOfQjLabel1;
    private javax.swing.JLabel numQ;
    private javax.swing.JLabel showattempted;
    private javax.swing.JButton submitjButton1;
    private javax.swing.JLabel wait;
    // End of variables declaration//GEN-END:variables
}
