
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIIT.Admin;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author AGARWAL-PC
 */

public class addstudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form addstudent
     */
    public addstudent() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        Logo = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        close = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        mailid = new javax.swing.JTextField();
        dob = new datechooser.beans.DateChooserCombo();
        jLabel10 = new javax.swing.JLabel();
        gendr = new javax.swing.JComboBox<>();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/NIIT.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Course");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("D.O.B.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contact");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("E-Mail ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID");

        course.setMaximumRowCount(5);
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "JAVA", "C", "CPP", "DotNet", "Php" }));
        course.setToolTipText("Select Student Course");
        course.setBorder(null);

        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });

        contact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactKeyPressed(evt);
            }
        });

        id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel8.setText("ENTER NEW STUDENT DATA");

        Add.setText("Add");
        Add.setToolTipText("Add this Student to Database");
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        Add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddKeyPressed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.setToolTipText("Reset Details");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Password");

        pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        mailid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        dob.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel10.setText("Gender");

    gendr.setMaximumRowCount(3);
    gendr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
    gendr.setToolTipText("Select Gender");
    gendr.setBorder(null);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(216, Short.MAX_VALUE)
            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
            .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(88, 88, 88))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Logo)
                    .addGap(139, 139, 139)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mailid))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(gendr, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(5, 5, 5)))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(8, 8, 8)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(gendr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mailid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(10, 10, 10))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
           this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyPressed
      String value = contact.getText();
    int l = value.length();
    if(l==10){
        if(evt.getKeyChar()== 8)
            contact.setEditable(true);
        else
            contact.setEditable(false);
    }
    else if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyChar()== 8)) {
        contact.setEditable(true);
        } 
    else {
        contact.setEditable(false);
    }
    }//GEN-LAST:event_contactKeyPressed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
       Calendar dt1 = GregorianCalendar.getInstance(); 
         dt1.set(2000,Calendar.JANUARY,01);
           dob.setSelectedDate(dt1);
         name.setText(null);
          course.setSelectedIndex(0);
          gendr.setSelectedIndex(0); 
            contact.setText(null);
            id.setText(null);
            mailid.setText(null);
            pass.setText(null);
                    // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
     String value = name.getText();
       
    if ((evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z')||(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z')||(evt.getKeyChar()== 32)||(evt.getKeyChar()== 8)) {
        name.setEditable(true);
        } 
    else {
        name.setEditable(false);
    }       
    }//GEN-LAST:event_nameKeyPressed

    private void AddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
               if(name.getText().isEmpty()||contact.getText().isEmpty()|id.getText().isEmpty()||pass.getText().isEmpty()||mailid.getText().isEmpty())
                JOptionPane.showMessageDialog(this,"Incomplete Details");
        else
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root",""); 
            Statement stmt = con.createStatement();
            ResultSet rs = null;
            Calendar dt;
            String nm,corse,numb,sid,passwd,mail,SQL, dobsend,gndr;

            
            nm= name.getText();
            corse = course.getSelectedItem().toString();
             gndr = gendr.getSelectedItem().toString();
            numb = contact.getText();
            sid = id.getText();
            passwd = pass.getText();
            dt=dob.getSelectedDate();
               int year = dt.get(Calendar.YEAR);
                 int month = dt.get(Calendar.MONTH);
                  month++;
                   int day = dt.get(Calendar.DAY_OF_MONTH);
             dobsend=Integer.toString(day)+"/"+Integer.toString(month)+"/"+Integer.toString(year);
               System.out.printf(dobsend);
              
               
           mail = mailid.getText();
          
            EmailValidator emailValidator = new EmailValidator();  
            ValidatePhoneNumber phoneValidator = new ValidatePhoneNumber();
            ValidateStudent_id idValidator = new ValidateStudent_id();
          
            if("Select".equalsIgnoreCase((String) course.getSelectedItem())){
                JOptionPane.showMessageDialog(this,"Choose a Valid Course","Error",JOptionPane.ERROR_MESSAGE);
            }
            else if("Select".equalsIgnoreCase((String) gendr.getSelectedItem())){
                JOptionPane.showMessageDialog(this,"Please Choose Gender","Error",JOptionPane.ERROR_MESSAGE);
            }            
            else if(!phoneValidator.validate(contact.getText().trim())){
         JOptionPane.showMessageDialog(this,"Invalid Contact Number","Error",JOptionPane.ERROR_MESSAGE);
               }
            
            else if(!emailValidator.validate(mailid.getText().trim())) {
         JOptionPane.showMessageDialog(this,"Invalid E-Mail ID","Error",JOptionPane.ERROR_MESSAGE);
               }
            else if(!idValidator.validate(id.getText().trim())) {
         JOptionPane.showMessageDialog(this,"Invalid Student ID","Error",JOptionPane.ERROR_MESSAGE);
               }
                     
           else if(pass.getText().length()<8){
                JOptionPane.showMessageDialog(this,"Password should be atleast 8 characters longE","Error",JOptionPane.ERROR_MESSAGE);
           }
            else 
            {
    SQL = "INSERT INTO student_info(id,pass,name,course,dob,gender,contact,mail) VALUES ('" +sid+ "','" +passwd+ "','" +nm+ "','" +corse+ "','" +dobsend+ "','" +gndr+ "','" +numb+ "','" +mail+ "')";
             
     stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(this,"Success","Submit",JOptionPane.INFORMATION_MESSAGE);
            name.setText(null);
                Calendar aDate = Calendar.getInstance();
        Calendar dt1 = GregorianCalendar.getInstance(); 
         dt1.set(2000,Calendar.JANUARY,01);
           dob.setSelectedDate(dt1);
            contact.setText(null);
            id.setText(null);
            mailid.setText(null);
            pass.setText(null);
            course.setSelectedIndex(0);
            gendr.setSelectedIndex(0);
        }
      } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
        }       // TODO add your handling code here:

        }
    }//GEN-LAST:event_AddKeyPressed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
       
       if(name.getText().isEmpty()||contact.getText().isEmpty()|id.getText().isEmpty()||pass.getText().isEmpty()||mailid.getText().isEmpty())
                JOptionPane.showMessageDialog(this,"Incomplete Details");
        else
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root",""); 
            Statement stmt = con.createStatement();
            ResultSet rs = null;
            Calendar dt;
            String nm,corse,numb,sid,passwd,mail,SQL, dobsend,gndr;

            
            nm= name.getText();
            corse = course.getSelectedItem().toString();
              gndr = gendr.getSelectedItem().toString();
            numb = contact.getText();
            sid = id.getText();
            passwd = pass.getText();
            dt=dob.getSelectedDate();
             
               int year = dt.get(Calendar.YEAR);
                 int month = dt.get(Calendar.MONTH);
                  month++;
                  int day = dt.get(Calendar.DAY_OF_MONTH);
             dobsend=Integer.toString(day)+"/"+Integer.toString(month)+"/"+Integer.toString(year);
                             
               
           mail = mailid.getText();
          
            EmailValidator emailValidator = new EmailValidator();  
            ValidatePhoneNumber phoneValidator = new ValidatePhoneNumber();
            ValidateStudent_id idValidator = new ValidateStudent_id();
          
            if("Select".equalsIgnoreCase((String) course.getSelectedItem())){
                JOptionPane.showMessageDialog(this,"Choose a Valid Course","Error",JOptionPane.ERROR_MESSAGE);
            }
           else if("Select".equalsIgnoreCase((String) gendr.getSelectedItem())){
                JOptionPane.showMessageDialog(this,"Please Choose Gender","Error",JOptionPane.ERROR_MESSAGE);
            } 
            
            else if(!phoneValidator.validate(contact.getText().trim())){
         JOptionPane.showMessageDialog(this,"Invalid Contact Number","Error",JOptionPane.ERROR_MESSAGE);
               }
            
            else if(!emailValidator.validate(mailid.getText().trim())) {
         JOptionPane.showMessageDialog(this,"Invalid E-Mail ID","Error",JOptionPane.ERROR_MESSAGE);
               }
            else if(!idValidator.validate(id.getText().trim())) {
         JOptionPane.showMessageDialog(this,"Invalid Student ID","Error",JOptionPane.ERROR_MESSAGE);
               }
                     
           else if(pass.getText().length()<8){
                JOptionPane.showMessageDialog(this,"Password should be atleast 8 characters longE","Error",JOptionPane.ERROR_MESSAGE);
           }
            else 
            {
    SQL = "INSERT INTO student_info(id,pass,name,course,dob,gender,contact,mail) VALUES ('" +sid+ "','" +passwd+ "','" +nm+ "','" +corse+ "','" +dobsend+ "','" +gndr+ "','" +numb+ "','" +mail+ "')";
             
     stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(this,"Success","Submit",JOptionPane.INFORMATION_MESSAGE);
            name.setText(null);
                Calendar aDate = Calendar.getInstance();
           Calendar dt1 = GregorianCalendar.getInstance(); 
         dt1.set(2000,Calendar.JANUARY,01);
           dob.setSelectedDate(dt1);
            contact.setText(null);
            id.setText(null);
            mailid.setText(null);
            pass.setText(null);
            course.setSelectedIndex(0);
            gendr.setSelectedIndex(0);
        }
      } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
        }       // TODO add your handling code here:

    }//GEN-LAST:event_AddMouseClicked

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
            String value = id.getText();
    int l = value.length();
    if(l==13){
        if(evt.getKeyChar()== 8)
            id.setEditable(true);
        else
            id.setEditable(false);
    }
    else if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')||(evt.getKeyChar()== 8)||(evt.getKeyChar()=='s')||(evt.getKeyChar()=='S')) {
        id.setEditable(true);
        } 
    else {
        id.setEditable(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyPressed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Reset;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> course;
    private datechooser.beans.DateChooserCombo dob;
    private javax.swing.JComboBox<String> gendr;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mailid;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables

    
}
