/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIIT.Admin;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AGARWAL-PC
 */
public class Q_info extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    String flg="0";
     ViewAllQ setLbl;
    public Q_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        viewall = new javax.swing.JButton();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/NIIT.png"))); // NOI18N

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/Icon/back-icon.png"))); // NOI18N
        close.setBorder(null);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/Icon/help_book-512.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Questions Database");

        Add.setText("Add New Question");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setText("Update Question");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete Question");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        viewall.setText("View all Question");
        viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(viewall, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewall, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404)
                .addComponent(Logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
         ViewAllQ v = new ViewAllQ();
         this.getParent().add(v);
        choose1 c=new choose1(v);
         this.getParent().add(c);
        setLbl=v;
         flg="1";
        setLbl.label.setText(flg);
        Dimension desktop = this.getSize();
        Dimension jinternalFrame = c.getSize();
        int width = (desktop.width - jinternalFrame.width)/2;
        int height = (desktop.height - jinternalFrame.height)/2;
        
         v.setVisible(true); 
          v.PBar.setVisible(false);
           v.head.setVisible(false);
        c.setVisible(true);    
               v.setLayer(0);
                c.setLayer(1);        
        try {
             c.setSelected(true);
            c.setLocation(width,height); 
            v.setMaximum(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(s_info.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.toFront();
   //Icon icon = new ImageIcon(ApplicationManager.getApplicationImage().getImage());
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       enterQues e  = new enterQues();
        this.getParent().add(e);
        Questions q = new Questions(e);
        this.getParent().add(q);
        e.setVisible(true);
        Dimension desktop = this.getSize();
        Dimension jinternalFrame = q.getSize();
        int width = (desktop.width - jinternalFrame.width)/2;
        int height = (desktop.height - jinternalFrame.height)/2;
        q.setVisible(true);
        e.setLayer(0);
        q.setLayer(1);
        try {
            e.setMaximum(true);
            q.setSelected(true);
            q.setLocation(width,height);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(s_info.class.getName()).log(Level.SEVERE, null, ex);
        } q.toFront();
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
             ViewAllQ v = new ViewAllQ();
         this.getParent().add(v);
        choose1 c=new choose1(v);
         this.getParent().add(c);
        
         setLbl=v;
         flg="2";
        setLbl.label.setText(flg);
       
        Dimension desktop = this.getSize();
        Dimension jinternalFrame = c.getSize();
        int width = (desktop.width - jinternalFrame.width)/2;
        int height = (desktop.height - jinternalFrame.height)/2;
        
         v.setVisible(true); 
          v.PBar.setVisible(false);
           v.head.setVisible(false);
        c.setVisible(true);    
               v.setLayer(0);
                c.setLayer(1);        
        try {
             c.setSelected(true);
            c.setLocation(width,height); 
            v.setMaximum(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(s_info.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.toFront();
   //Icon icon = new ImageIcon(ApplicationManager.getApplicationImage().getImage());

    }//GEN-LAST:event_DeleteActionPerformed

    private void viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallActionPerformed
         ViewAllQ v = new ViewAllQ();
         this.getParent().add(v);
        choose1 c=new choose1(v);
         this.getParent().add(c);
         setLbl=v;
         flg="3";
        setLbl.label.setText(flg);
       
        
        Dimension desktop = this.getSize();
        Dimension jinternalFrame = c.getSize();
        int width = (desktop.width - jinternalFrame.width)/2;
        int height = (desktop.height - jinternalFrame.height)/2;
        
         v.setVisible(true); 
          v.PBar.setVisible(false);
           v.head.setVisible(false);
        c.setVisible(true);    
               v.setLayer(0);
                c.setLayer(1);        
        try {
             c.setSelected(true);
            c.setLocation(width,height); 
            v.setMaximum(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(s_info.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.toFront();
   //Icon icon = new ImageIcon(ApplicationManager.getApplicationImage().getImage());
   
    }//GEN-LAST:event_viewallActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Update;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewall;
    // End of variables declaration//GEN-END:variables
}
