/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIIT.Admin;

import NIIT.stud.GroupButtonUtils;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author AGARWAL-PC
 */
public class Q_type extends javax.swing.JInternalFrame {
  String Sel, SQL, course;  
  int conceptCount = 0;
  
    Connection con;
    ResultSet rs;
    Statement stmt;
    JLabel Cname[];
    JRadioButton Button[];
    /** 
     * Creates new form Q_type
     */
    ButtonGroup group = new ButtonGroup();
    GroupButtonUtils select = new GroupButtonUtils();
    
    ActionListener l;
    enterQues setLbl;
    UpdateQues setLbl1;
    
    public Q_type(enterQues set, String course) {
        initComponents();
        this.toFront();
        this.setLayer(2);
        if(course.equalsIgnoreCase("c"))
            this.course = "clang";
        else
            this.course = course;
        setLbl = set;
        this.setVisible(true);     
        
        l = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setLbl.QuesCateg.setText(select.getSelectedButtonText(group));
                }
        };
        createConceptLabels();
    }

     public Q_type(UpdateQues set, String course) {
        initComponents();
        this.toFront();
        this.setLayer(2);
        if(course.equalsIgnoreCase("c"))
            this.course = "clang";
        else
            this.course = course;
        setLbl1 = set;
        this.setVisible(true);
        
        l = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setLbl1.QuesCateg.setText(select.getSelectedButtonText(group));
                }
        };
        createConceptLabels();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myGroup = new javax.swing.ButtonGroup();
        my1 = new javax.swing.ButtonGroup();
        conceptPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        conceptNameJLabel = new javax.swing.JLabel();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/NIIT.png"))); // NOI18N
        setVisible(true);

        jButton2.setText("O.K.");
        jButton2.setToolTipText("Select This Type");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        conceptNameJLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        conceptNameJLabel.setText("Concepts Type");

        javax.swing.GroupLayout conceptPanelLayout = new javax.swing.GroupLayout(conceptPanel);
        conceptPanel.setLayout(conceptPanelLayout);
        conceptPanelLayout.setHorizontalGroup(
            conceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conceptPanelLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conceptPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(conceptNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conceptPanelLayout.setVerticalGroup(
            conceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conceptPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(conceptNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(conceptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(conceptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(conceptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
   // RBans = select.getSelectedButtonText(group);
    
   
    void createConceptLabels(){
        try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root","");

        SQL = "SELECT * FROM `concepts " +course+ "`";

        stmt = con.createStatement();
        rs = stmt.executeQuery(SQL);

        while(rs.next())
            conceptCount++;

        int cnt = 0, locx = 30, locy = 75;
        
        Cname = new JLabel[conceptCount];
        Button = new JRadioButton[conceptCount];
        
        Dimension panelSize = new Dimension(600, conceptCount*26+130);
        Dimension frameSize = new Dimension(600, conceptCount*26+180);
               
        conceptPanel.setPreferredSize(panelSize);
        conceptPanel.setMaximumSize(panelSize);
        conceptPanel.setMinimumSize(panelSize);
        this.setSize(frameSize);
        this.repaint();
        rs.first();
        while(true){
            Cname[cnt] = new JLabel(rs.getString("concept name"));
            Button[cnt] = new JRadioButton(Integer.toString(cnt+1));
            Button[cnt].addActionListener(l);
            group.add(Button[cnt]);
            conceptPanel.add(Cname[cnt]);
            conceptPanel.add(Button[cnt]);
            
            Button[cnt].setSize(40,20);
            Button[cnt].setBorder(null);
            Button[cnt].setLocation(locx, locy);
            
            Cname[cnt].setSize(600,20);
            Cname[cnt].setBorder(null);
            Cname[cnt].setLocation(locx+60, locy);
            locy += 26;
            cnt++;
            if(!rs.next())
                break;
        }
          
        conceptPanel.repaint();
          
      } catch (ClassNotFoundException | SQLException ex) {
          Logger.getLogger(Q_type.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           this.setVisible(false);       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);     
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conceptNameJLabel;
    private javax.swing.JPanel conceptPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.ButtonGroup my1;
    private javax.swing.ButtonGroup myGroup;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
