/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIIT.Admin;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dev
 */
 
public class UpdateQues extends javax.swing.JInternalFrame {
    String Sel;
   /**
     * Creates new form enterQues
     */
    Connection con;
    Statement stmt;
    ResultSet rs;
    static final String JDBC_DRIVER ="com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/niitdb";
     
       String tbl,c,e,f,g,h,i,j,k,info, course;
    public UpdateQues() {
        initComponents(); 
                           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ans = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c_type = new javax.swing.JLabel();
        Select_type = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        QuesCateg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        A = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        C = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        B = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        D = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/NIIT.png"))); // NOI18N

        jLabel2.setText("Question");

        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel4.setText("Correct Answer");

        ans.setMaximumRowCount(4);
        ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel5.setText("Update Question for");

        c_type.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N

        Select_type.setText("Select Type");
        Select_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_typeActionPerformed(evt);
            }
        });

        jLabel12.setText("c.");

        jLabel6.setText("a.");

        jLabel7.setText("b.");

        jLabel9.setText("d.");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        QuesCateg.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        QuesCateg.setText("None");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        question.setColumns(20);
        question.setLineWrap(true);
        question.setRows(5);
        question.setWrapStyleWord(true);
        question.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(question);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        A.setColumns(20);
        A.setLineWrap(true);
        A.setRows(5);
        A.setWrapStyleWord(true);
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(A);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        C.setColumns(20);
        C.setLineWrap(true);
        C.setRows(5);
        C.setWrapStyleWord(true);
        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(C);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        B.setColumns(20);
        B.setLineWrap(true);
        B.setRows(5);
        B.setWrapStyleWord(true);
        B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(B);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        D.setColumns(20);
        D.setLineWrap(true);
        D.setRows(5);
        D.setWrapStyleWord(true);
        D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(D);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select_type, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(QuesCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_type, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Select_type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuesCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    void setLabel(String tmp,String tmp2) {
       tbl=tmp2;
       info=tmp;
       
        try {
            Class.forName("com.mysql.jdbc.Driver");  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    try { 
        con=(Connection) DriverManager.getConnection(DB_URL,"root","");
    } catch (SQLException ex) {
        Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        stmt=(Statement) con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
    }  
    if("c".equalsIgnoreCase(tbl)){
                 tbl=tbl+"lang";
             } 
    String sql = "Select * from "+tbl+" where ques='"+info+"'";
 
 // String sql = "Select * from JAVA where ques='CHECK'";
     rs = null;
       try{  rs = stmt.executeQuery(sql);
              
        } catch (SQLException ex) {
            Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
              
             while (rs.next())
            {
                  c=rs.getString("ques");
                  e=rs.getString("a");
                  f=rs.getString("b");
                  g=rs.getString("c");
                  h=rs.getString("d");
                  i=rs.getString("ans");
                  j=rs.getString("category");
             }       } catch (SQLException ex) {       
            Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
        }
      question.setText(c);
      question.setForeground(Color.BLACK);
      question.setEnabled(false);
        A.setText(e);
        A.setForeground(Color.BLACK);
          B.setText(f);
          B.setForeground(Color.BLACK);
            C.setText(g);
            C.setForeground(Color.BLACK);
              D.setText(h);
              D.setForeground(Color.BLACK);
                ans.setSelectedItem(i);
                  QuesCateg.setText(j);
                  QuesCateg.setForeground(Color.BLACK);
                  
       
    }
            
    
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
           this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String SQL;
        String s1=question.getText();
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = 0;
        if(!"question".equals(s1))
        dialogResult = JOptionPane.showConfirmDialog(this,"Are you sure to Update this Question","Warning",dialogButton,JOptionPane.WARNING_MESSAGE,null);
        if(dialogResult == JOptionPane.YES_OPTION)

        try{
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/niitdb","root","");
            stmt=con.createStatement();
            if("question".equals(s1))
            JOptionPane.showMessageDialog(this,"Please Enter Details","Empty!",JOptionPane.ERROR_MESSAGE);
            else{

                String quest,opt1,opt2,opt3,opt4,answ,typ;
                
                quest= question.getText();
                opt1 = A.getText();
                opt2 = B.getText();
                opt3 = C.getText();
                opt4 = D.getText();
               answ = ans.getSelectedItem().toString();
                typ= QuesCateg.getText();
                 if(question.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Please Enter Question","Error",JOptionPane.ERROR_MESSAGE);
                }
               else 
                     if(A.getText().isEmpty()||B.getText().isEmpty()||C.getText().isEmpty()||D.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Fill All Details","Error",JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    SQL="UPDATE "+tbl+" SET ques = '"+quest+"',a = '"+opt1+"',b='"+opt2+"',c='"+opt3+"',d='"+opt4+"',ans='"+answ+"',category = '"+typ+"' WHERE ques = '"+quest+"' ";
                    stmt.executeUpdate(SQL);
                    question.setText("question");
                    question.setEnabled(false);
                      A.setText(null);
                      B.setText(null);
                      C.setText(null);
                      D.setText(null);
                      QuesCateg.setText(null);
                      ans.setSelectedIndex(0);
                    
                    JOptionPane.showMessageDialog(this,"Data Updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void Select_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_typeActionPerformed
        Q_type selectType = new Q_type(this,c_type.getText());
        
        Dimension screen = new Dimension(this.getSize());
        Dimension frameSize = new Dimension(selectType.getSize());
        
        int width = (screen.width - frameSize.width)/2;
        int height = (screen.height - frameSize.height)/2;
        selectType.setLocation(width, height);
        
        this.getParent().add(selectType);
    }//GEN-LAST:event_Select_typeActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea A;
    private javax.swing.JTextArea B;
    private javax.swing.JTextArea C;
    private javax.swing.JTextArea D;
    protected javax.swing.JLabel QuesCateg;
    private javax.swing.JButton Select_type;
    private javax.swing.JComboBox<String> ans;
    protected javax.swing.JLabel c_type;
    protected javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea question;
    protected javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
