/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NIIT.Admin;

import NIIT.stud.GroupButtonUtils;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AGARWAL-PC
 */
public class ViewAllS extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewAllS
     */
  
    Connection con;
    Statement stmt;
    static final String JDBC_DRIVER ="com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/niitdb";
    DefaultTableModel model= new DefaultTableModel(new String[]{"Student ID" , "Name","Course"},0);
    ButtonGroup group1 = new ButtonGroup();
   ViewStud setLbl1;
  int count=0;
    GroupButtonUtils corse = new GroupButtonUtils();
    protected Timer t;
    protected ActionListener al;
   
    public ViewAllS() {
        initComponents();
        jLabel2.setVisible(false);
        al = new ActionListener(){ 
    
              public void actionPerformed(ActionEvent ae){
                  if(PBar.getValue()<100){
                       
                    PBar.setValue(PBar.getValue()+5);
                   }
                 else{t.stop();
                      jLabel2.setVisible(true);
                      head.setVisible(false);
                      PBar.setVisible(false);
                       Color color = UIManager.getColor("Table.gridColor");
                MatteBorder border = new MatteBorder(1, 1, 0, 0,Color.BLUE);
                 jTable1.setBorder(border);
                        jTable1.setModel(model);
                       if(count>0)
                  JOptionPane.showMessageDialog(null,"Successfully Fetched Data","Success",JOptionPane.INFORMATION_MESSAGE);    
                   else
                  JOptionPane.showMessageDialog(null,"No Data Found","Empty",JOptionPane.OK_CANCEL_OPTION);   
                     
                  }
              } 
         };
         t=new Timer(100,al);
         
    }    

    public ViewAllS(ViewStud v) {
         initComponents(); 
          setLbl1=v;  
          // v.toFront();
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){

            public boolean isCellEditable(int row, int column){
                return false;}
        };
        jPanel1 = new javax.swing.JPanel();
        PBar = new javax.swing.JProgressBar();
        head = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JButton();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/NIIT.png"))); // NOI18N

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Course"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        PBar.setBackground(new java.awt.Color(0, 0, 0));
        PBar.setForeground(new java.awt.Color(255, 255, 255));
        PBar.setOpaque(true);
        PBar.setStringPainted(true);

        head.setFont(new java.awt.Font("Swis721 Hv BT", 0, 11)); // NOI18N
        head.setText("Please Wait Fetching Data from DataBase ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Student Database");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(PBar, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(head))
        );

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NIIT/Admin/Icon/back-icon.png"))); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
  this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        label.setText(String.valueOf(model.getValueAt(jTable1.getSelectedRow(),0)));
         String tmp=label.getText();
        label.setVisible(false);
        
        
              DataModel d = new DataModel();
                       d.setData(tmp);
               ViewStud a = new ViewStud(d);
            this.getParent().add(a);
              a.setVisible(true);   
        try {
            a.setMaximum(true);
            a.setSelected(true);
//            setLbl1.setLabel();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(s_info.class.getName()).log(Level.SEVERE, null, ex);
       }   
    }//GEN-LAST:event_jTable1MouseClicked
  void setLabel(String s1) {
      JOptionPane.showMessageDialog(this,"You Choose Students List of '"+s1+"' Course(s)","Success",JOptionPane.INFORMATION_MESSAGE);   
  try {
            Class.forName("com.mysql.jdbc.Driver");  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
        }
    try { 
        con=(Connection) DriverManager.getConnection(DB_URL,"root","");
    } catch (SQLException ex) {
        Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        stmt=(Statement) con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);        // TODO add your handling code here:
    } catch (SQLException ex) {
        Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
    }
 String sql = "Select * from student_info where course='"+s1+"' order by id ASC";
  String sql1 = "Select * from student_info order by id asc";
ResultSet rs = null;
        try { if("All".equalsIgnoreCase(s1)){
              rs = stmt.executeQuery(sql1);}
            else {
               rs = stmt.executeQuery(sql);
           }
           
        } catch (SQLException ex) {
            Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
                count++;
            }
            rs.beforeFirst();
              
             while (rs.next())
            {
                String d = rs.getString("id");
                String e = rs.getString("name");
                String f = rs.getString("course");
                
                model.addRow(new Object[]{d,e,f});
            }       } catch (SQLException ex) {       
            Logger.getLogger(ViewAllS.class.getName()).log(Level.SEVERE, null, ex);
        }
   close.setEnabled(true);
      }
          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JProgressBar PBar;
    protected javax.swing.JButton close;
    protected javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    protected javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

    private static class ActionListner {

        public ActionListner() {
        }
    }
}
